"""Generate the Lean instance modules for a resolved clause dump (P2/P3).

Input: the output directory of `lean_static_resolve.py` (graph.json +
witnesses.txt). Output, under lean/:
  data/<key>/witnesses.txt                    (copy)
  Biplanar/Instances/<Name>/Defs.lean         graph literal, include_str of the
                                              witnesses, F := mkCNF G ws
                                              (mkCNFSym G ws gens when the dump
                                              carried automorphism generators)
  Biplanar/Instances/<Name>.lean              LRAT import + final theorem
and a reminder to register ("<key>", Biplanar.<Name>.F) in
Biplanar/Instances.lean. With --cube the theorem is the cube-leaf variant
(`Cube.leafCNF cube F`), used for mechanics tests on pinned instances.

Usage:
  .venv/bin/python verifier/lean_instance.py RESOLVE_DIR --key k9c --name K9Control \
      [--cube -1 -2 ...] [--doc "K9-core negative control ..."]
"""
from __future__ import annotations

import argparse
import json
import os
import shutil

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
LEAN = os.path.join(ROOT, "lean")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("resolve_dir")
    ap.add_argument("--key", required=True, help="registry key, e.g. k9c")
    ap.add_argument("--name", required=True, help="Lean module name, e.g. K9Control")
    ap.add_argument("--cube", nargs="*", type=int, default=None,
                    help="DIMACS cube literals (leaf variant)")
    ap.add_argument("--doc", default="")
    ap.add_argument("--no-counters", action="store_true",
                    help="use the counter-free formula mkCNF₀ (theorem under (H2) "
                         "only); valid when the LRAT core uses no cardinality clause")
    args = ap.parse_args()

    g = json.load(open(os.path.join(args.resolve_dir, "graph.json")))
    gens = g.get("gens") or []
    sym = bool(gens)
    wpath = os.path.join(args.resolve_dir, "witnesses.txt")
    nwit = sum(1 for _ in open(wpath))
    units = g.get("extra_units") or []
    cube = args.cube if args.cube is not None else units
    if units and not args.cube:
        print(f"note: dump had cube units {units}; using them as the cube")

    ddir = os.path.join(LEAN, "data", args.key)
    os.makedirs(ddir, exist_ok=True)
    shutil.copy(wpath, os.path.join(ddir, "witnesses.txt"))
    mdir = os.path.join(LEAN, "Biplanar", "Instances", args.name)
    os.makedirs(mdir, exist_ok=True)

    edges = ", ".join(f"({u}, {v})" for u, v in g["edges"])
    if sym:
        mk = ("Biplanar.mkCNFSym₀" if args.no_counters else "Biplanar.mkCNFSym")
        mk_args = " G ws gens"
        gens_lean = ",\n   ".join(
            "⟨[" + ", ".join(map(str, gg["vperm"])) + "], ["
            + ", ".join(map(str, gg["eperm"])) + "]⟩" for gg in gens)
        gens_def = f'''
/-- The {len(gens)} automorphism generators whose lex symmetry-breaking
    clauses `F` contains, in the order their activity variables are laid
    out. `Gen.ok G` re-checks every one of them against `G`. -/
def gens : List Biplanar.Gen :=
  [{gens_lean}]
'''
    else:
        mk = "Biplanar.mkCNF₀" if args.no_counters else "Biplanar.mkCNF"
        mk_args = " G ws"
        gens_def = ""
    defs = f'''import Biplanar.{"SymDefs" if sym else "Basic"}

/-! Instance `{args.key}` ({g["name"]}): {args.doc}
    n = {g["n"]}, m = {len(g["edges"])}, cap = {g["cap"]}; {nwit} witnesses{f"; {len(gens)} symmetry generators" if sym else ""}
    (generated by verifier/lean_instance.py from {os.path.abspath(args.resolve_dir)}).
    Formula: `{mk}`{" (counter-free: the LRAT core used no cardinality clause)" if args.no_counters else ""}. -/

namespace Biplanar.{args.name}

def G : Biplanar.Graph := ⟨{g["n"]}, [{edges}]⟩

def witnessStr : String := include_str "../../../data/{args.key}/witnesses.txt"

def ws : List Biplanar.Witness := Biplanar.parseWitnesses witnessStr
{gens_def}
def F : Std.Sat.CNF Nat := {mk}{mk_args}

end Biplanar.{args.name}
'''
    open(os.path.join(mdir, "Defs.lean"), "w").write(defs)

    if sym and cube and not args.no_counters:
        raise SystemExit("sym-on cube leaves are supported only with "
                         "--no-counters (Lean: not_biplanar_on_cube_of_unsat_sym₀)")
    if sym and not cube:
        head = f'''import Biplanar.Instances.{args.name}.Defs
import Biplanar.Sym

/-! Certified non-biplanarity of `{args.key}` ({args.doc}) from a
    SYMMETRY-BROKEN formula: `F` carries the lex clauses of {len(gens)}
    automorphism generators, proved sound in `Biplanar/Sym.lean`, so the
    theorem needs the third elementary hypothesis (H3) — planarity is an
    isomorphism invariant. Certificate `data/{args.key}/F.lrat` refutes the
    DIMACS file written by
    `lake exe biplanar-export {args.key} data/{args.key}/F.cnf`. -/

namespace Biplanar.{args.name}

-- `native_decide` reflection is cheap at run time, but a declaration's
-- checks share one elaboration budget and the default trips on large
-- witness lists. Raising it changes no axiom.
set_option maxHeartbeats 2000000

lrat_reflect_cnf F_unsat (Biplanar.{args.name}.F) "data/{args.key}/F.lrat"
'''
        if args.no_counters:
            thm = head + f'''
/-- **Conditional non-biplanarity theorem (Stage 2, counter-free).** For
    every predicate `planar` on edge lists satisfying the elementary
    direction of Kuratowski's theorem (H2) and isomorphism invariance (H3),
    the graph `G` admits no partition of its edges into two `planar` parts.
    Euler's bound is not needed. -/
theorem not_biplanar (planar : List Biplanar.Edge → Prop)
    (H2 : ∀ (S : List Biplanar.Edge) (c : Biplanar.KurCert), c.valid S = true → ¬ planar S)
    (H3 : Biplanar.IsoInvariant G planar) :
    ¬ Biplanar.Biplanar planar G :=
  Biplanar.not_biplanar_of_unsat_sym₀ G ws gens (by native_decide) (by native_decide)
    (by native_decide) F_unsat planar H2 H3

#print axioms not_biplanar

end Biplanar.{args.name}
'''
        else:
            thm = head + f'''
/-- **Conditional non-biplanarity theorem (Stage 2).** For every predicate
    `planar` on edge lists satisfying Euler's bound (H1), the elementary
    direction of Kuratowski's theorem (H2) and isomorphism invariance (H3),
    the graph `G` admits no partition of its edges into two `planar` parts. -/
theorem not_biplanar (planar : List Biplanar.Edge → Prop)
    (H1 : ∀ S : List Biplanar.Edge, S.Nodup → (∀ e ∈ S, e.1 < e.2 ∧ e.2 < G.n) →
      planar S → S.length ≤ 3 * G.n - 6)
    (H2 : ∀ (S : List Biplanar.Edge) (c : Biplanar.KurCert), c.valid S = true → ¬ planar S)
    (H3 : Biplanar.IsoInvariant G planar) :
    ¬ Biplanar.Biplanar planar G :=
  Biplanar.not_biplanar_of_unsat_sym G ws gens (by native_decide) (by native_decide)
    (by native_decide) F_unsat planar H1 H2 H3

#print axioms not_biplanar

end Biplanar.{args.name}
'''
    elif sym and cube:
        cube_lean = ", ".join(
            f"({abs(l) - 1}, {'true' if l > 0 else 'false'})" for l in cube)
        thm = f'''import Biplanar.Instances.{args.name}.Defs
import Biplanar.Sym

/-! Cube-leaf variant for the symmetry-broken formula of `{args.key}`. -/

namespace Biplanar.{args.name}

def cube : LRATCatcher.Cube := [{cube_lean}]

-- `native_decide` reflection is cheap at run time, but a declaration's
-- checks share one elaboration budget and the default trips on large
-- witness lists. Raising it changes no axiom.
set_option maxHeartbeats 2000000

lrat_reflect_cnf leaf_unsat (LRATCatcher.Cube.leafCNF Biplanar.{args.name}.cube Biplanar.{args.name}.F) "data/{args.key}/F.lrat"

/-- No lex-minimal biplanar partition of `G` agrees with the cube. -/
theorem not_biplanar_on_cube (planar : List Biplanar.Edge → Prop)
    (H2 : ∀ (S : List Biplanar.Edge) (c : Biplanar.KurCert), c.valid S = true → ¬ planar S) :
    ¬ ∃ σ : Nat → Bool, σ 0 = false ∧ Biplanar.lexOK G gens σ = true ∧
        cube.sat (Biplanar.valSym G gens G.edges.length σ) = true ∧
        planar (Biplanar.part G σ false) ∧ planar (Biplanar.part G σ true) :=
  Biplanar.not_biplanar_on_cube_of_unsat_sym₀ G ws gens cube (by native_decide)
    (by native_decide) (by native_decide) leaf_unsat planar H2

#print axioms not_biplanar_on_cube

end Biplanar.{args.name}
'''
    elif cube:
        cube_lean = ", ".join(
            f"({abs(l) - 1}, {'true' if l > 0 else 'false'})" for l in cube)
        thm = f'''import Biplanar.Instances.{args.name}.Defs
import Biplanar.Lift

/-! Cube-leaf variant for `{args.key}`: the formula `Cube.leafCNF cube F`
    (cube unit clauses first, then `F`), certificate `data/{args.key}/F.lrat`
    produced by `cadical --lrat --no-binary --no-factor` on the DIMACS file
    written by `lake exe biplanar-export {args.key} data/{args.key}/F.cnf {" ".join(map(str, cube))}`. -/

namespace Biplanar.{args.name}

def cube : LRATCatcher.Cube := [{cube_lean}]

-- `native_decide` reflection is cheap at run time, but a declaration's
-- checks share one elaboration budget and the default trips on large
-- witness lists. Raising it changes no axiom.
set_option maxHeartbeats 2000000

lrat_reflect_cnf leaf_unsat (LRATCatcher.Cube.leafCNF Biplanar.{args.name}.cube Biplanar.{args.name}.F) "data/{args.key}/F.lrat"

/-- No biplanar partition of `G` with edge 0 in part 1 agrees with the cube
    (the leaf statement; the part-swap normalisation `σ 0 = false` is the
    base formula's unit clause and is discharged once at the top level). -/
theorem not_biplanar_on_cube (planar : List Biplanar.Edge → Prop)
    (H1 : ∀ S : List Biplanar.Edge, S.Nodup → (∀ e ∈ S, e.1 < e.2 ∧ e.2 < G.n) →
      planar S → S.length ≤ 3 * G.n - 6)
    (H2 : ∀ (S : List Biplanar.Edge) (c : Biplanar.KurCert), c.valid S = true → ¬ planar S) :
    ¬ ∃ σ : Nat → Bool, σ 0 = false ∧ cube.sat (Biplanar.val G σ) = true ∧
        planar (Biplanar.part G σ false) ∧ planar (Biplanar.part G σ true) :=
  Biplanar.not_biplanar_on_cube_of_unsat G ws cube (by native_decide) (by native_decide)
    leaf_unsat planar H1 H2

#print axioms not_biplanar_on_cube

end Biplanar.{args.name}
'''
    elif args.no_counters:
        thm = f'''import Biplanar.Instances.{args.name}.Defs
import Biplanar.Lift

/-! Certified non-biplanarity of `{args.key}` ({args.doc}), counter-free
    formula. Certificate `data/{args.key}/F.lrat` (or a cube-and-conquer
    composition, see `Biplanar/Instances/{args.name}/`) refutes the DIMACS
    file written by `lake exe biplanar-export {args.key} data/{args.key}/F.cnf`. -/

namespace Biplanar.{args.name}

-- `native_decide` reflection is cheap at run time, but a declaration's
-- checks share one elaboration budget and the default trips on large
-- witness lists. Raising it changes no axiom.
set_option maxHeartbeats 2000000

lrat_reflect_cnf F_unsat (Biplanar.{args.name}.F) "data/{args.key}/F.lrat"

/-- **Conditional non-biplanarity theorem (Stage 1, counter-free).** For
    every predicate `planar` on edge lists satisfying the elementary direction
    of Kuratowski's theorem (H2), the graph `G` admits no partition of its
    edges into two `planar` parts. Euler's bound is not needed. -/
theorem not_biplanar (planar : List Biplanar.Edge → Prop)
    (H2 : ∀ (S : List Biplanar.Edge) (c : Biplanar.KurCert), c.valid S = true → ¬ planar S) :
    ¬ Biplanar.Biplanar planar G :=
  Biplanar.not_biplanar_of_unsat₀ G ws (by native_decide) (by native_decide) F_unsat planar H2

#print axioms not_biplanar

end Biplanar.{args.name}
'''
    else:
        thm = f'''import Biplanar.Instances.{args.name}.Defs
import Biplanar.Lift

/-! Certified non-biplanarity of `{args.key}` ({args.doc}).
    Certificate `data/{args.key}/F.lrat` produced by
    `cadical --lrat --no-binary --no-factor` on the DIMACS file written by
    `lake exe biplanar-export {args.key} data/{args.key}/F.cnf`. -/

namespace Biplanar.{args.name}

-- `native_decide` reflection is cheap at run time, but a declaration's
-- checks share one elaboration budget and the default trips on large
-- witness lists. Raising it changes no axiom.
set_option maxHeartbeats 2000000

lrat_reflect_cnf F_unsat (Biplanar.{args.name}.F) "data/{args.key}/F.lrat"

/-- **Conditional non-biplanarity theorem (Stage 1).** For every predicate
    `planar` on edge lists satisfying Euler's bound (H1) and the elementary
    direction of Kuratowski's theorem (H2), the graph `G` admits no partition
    of its edges into two `planar` parts. -/
theorem not_biplanar (planar : List Biplanar.Edge → Prop)
    (H1 : ∀ S : List Biplanar.Edge, S.Nodup → (∀ e ∈ S, e.1 < e.2 ∧ e.2 < G.n) →
      planar S → S.length ≤ 3 * G.n - 6)
    (H2 : ∀ (S : List Biplanar.Edge) (c : Biplanar.KurCert), c.valid S = true → ¬ planar S) :
    ¬ Biplanar.Biplanar planar G :=
  Biplanar.not_biplanar_of_unsat G ws (by native_decide) (by native_decide) F_unsat planar H1 H2

#print axioms not_biplanar

end Biplanar.{args.name}
'''
    open(os.path.join(mdir + ".lean"), "w").write(thm)
    print(f"wrote {mdir}/Defs.lean, {mdir}.lean, data/{args.key}/witnesses.txt ({nwit} lines)")
    print(f"NEXT: register (\"{args.key}\", Biplanar.{args.name}.F) in lean/Biplanar/Instances.lean "
          f"(import Biplanar.Instances.{args.name}.Defs), then from lean/:")
    cube_arg = (" " + " ".join(map(str, cube))) if cube else ""
    print(f"  lake exe biplanar-export {args.key} data/{args.key}/F.cnf{cube_arg}")
    print(f"  cadical --lrat --no-binary --no-factor data/{args.key}/F.cnf data/{args.key}/F.lrat")
    print(f"  ../tools/drat-trim/lrat-check data/{args.key}/F.cnf data/{args.key}/F.lrat")
    print(f"  lake build Biplanar.Instances.{args.name}")


if __name__ == "__main__":
    main()
