#!/usr/bin/env python3
"""Lean modules for the SPLIT route (F-038 §8): a sym-on, counter-free
refutation cut into cubes, each cube with its OWN witness set.

`Biplanar.not_biplanar_of_cover` (Biplanar/Sym.lean) composes over the
per-cube STATEMENTS, not over one formula, so leaf j may be refuted from its
own witnesses ws_j (the LRAT core of the Python-side solve of cube j) with its
own formula F_j := mkCNFSym₀ G ws_j gens and its own certificate. Memory and
certificate size then scale with the hardest cube, not with the instance.

Output under lean/Biplanar/Instances/<Name>/:
  Base.lean        G and gens (shared)
  Cubes.lean       cube1 … cubeL (named, so the dispatch in the main module
                   matches the leaf statements syntactically) and `cubes`
  W<j>.lean        witnessStr<j> (include_str data/<key>/w<j>.txt), ws<j>, F<j>
  Leaf<j>.lean     lrat_reflect_cnf leaf<j>_unsat (Cube.leafCNF cube<j> F<j>)
                   "data/<key>/leaf<j>.lrat" and the per-cube theorem leaf<j>
  Cover.lean       lrat_reflect_cnf cover_unsat (negCubesCNF cubes)
                   "data/<key>/cover.lrat"
and lean/Biplanar/Instances/<Name>.lean: not_biplanar by not_biplanar_of_cover.
Registry: one entry "<key>_<j>" -> Biplanar.<Name>.F<j> per leaf (the exporter
writes leaf j as `biplanar-export <key>_<j> leaf<j>.cnf <cube j literals>`).

Usage:
  lean_split_modules.py --key a4_m17s --name A4M17S --graph DIR/graph.json \
      --cubes DIR/cubes.json --doc "…"
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lean_registry import add as registry_add  # noqa: E402

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
LEAN = os.path.join(ROOT, "lean")

HB = """-- `native_decide` reflection is cheap at run time, but a declaration's
-- checks share one elaboration budget and the default trips on large
-- witness lists. Raising it changes no axiom.
set_option maxHeartbeats 2000000
"""


def lean_cube(lits):
    return "[" + ", ".join(f"({abs(l) - 1}, {'true' if l > 0 else 'false'})" for l in lits) + "]"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--key", required=True)
    ap.add_argument("--name", required=True)
    ap.add_argument("--graph", required=True, help="graph.json (n, edges, gens)")
    ap.add_argument("--cubes", required=True, help="JSON list of DIMACS cube literal lists")
    ap.add_argument("--doc", default="")
    ap.add_argument("--no-registry", action="store_true")
    a = ap.parse_args()

    g = json.load(open(a.graph))
    gens = g["gens"]
    assert gens, "the split route is for symmetry-broken formulas"
    cubes = json.load(open(a.cubes))
    L = len(cubes)
    ns = f"Biplanar.{a.name}"
    mdir = os.path.join(LEAN, "Biplanar", "Instances", a.name)
    os.makedirs(mdir, exist_ok=True)
    mod = f"Biplanar.Instances.{a.name}"

    edges = ", ".join(f"({u}, {v})" for u, v in g["edges"])
    gens_lean = ",\n   ".join(
        "⟨[" + ", ".join(map(str, gg["vperm"])) + "], ["
        + ", ".join(map(str, gg["eperm"])) + "]⟩" for gg in gens)
    open(os.path.join(mdir, "Base.lean"), "w").write(f'''import Biplanar.SymDefs

/-! Instance `{a.key}` (split route, {L} cubes): {a.doc}
    n = {g["n"]}, m = {len(g["edges"])}; {len(gens)} symmetry generators
    (generated by verifier/lean_split_modules.py). -/

namespace {ns}

def G : Biplanar.Graph := ⟨{g["n"]}, [{edges}]⟩

/-- The {len(gens)} automorphism generators whose lex symmetry-breaking
    clauses every leaf formula carries. `Gen.ok G` re-checks each of them. -/
def gens : List Biplanar.Gen :=
  [{gens_lean}]

end {ns}
''')
    cube_defs = "\n".join(f"def cube{j} : LRATCatcher.Cube := {lean_cube(c)}"
                          for j, c in enumerate(cubes, 1))
    open(os.path.join(mdir, "Cubes.lean"), "w").write(f'''import {mod}.Base

/-! The {L} cubes of `{a.key}` (DIMACS: {cubes}). -/

namespace {ns}

{cube_defs}

def cubes : List LRATCatcher.Cube := [{", ".join(f"cube{j}" for j in range(1, L + 1))}]

end {ns}
''')
    for j in range(1, L + 1):
        wfile = os.path.join(LEAN, "data", a.key, f"w{j}.txt")
        nwit = sum(1 for _ in open(wfile))
        open(os.path.join(mdir, f"W{j}.lean"), "w").write(f'''import {mod}.Base

/-! Leaf {j} of `{a.key}`: its own witness set ({nwit} witnesses, the LRAT core
    of the Python-side solve of cube {j}) and formula `F{j}`. -/

namespace {ns}

def witnessStr{j} : String := include_str "../../../data/{a.key}/w{j}.txt"

def ws{j} : List Biplanar.Witness := Biplanar.parseWitnesses witnessStr{j}

def F{j} : Std.Sat.CNF Nat := Biplanar.mkCNFSym₀ G ws{j} gens

end {ns}
''')
        open(os.path.join(mdir, f"Leaf{j}.lean"), "w").write(f'''import {mod}.W{j}
import {mod}.Cubes
import Biplanar.Sym

/-! Leaf {j} of {L}: cube `{cubes[j - 1]}` (DIMACS), refuted by
    `data/{a.key}/leaf{j}.lrat` (CaDiCaL on the DIMACS file written by
    `lake exe biplanar-export {a.key}_{j} data/{a.key}/leaf{j}.cnf {" ".join(map(str, cubes[j - 1]))}`). -/

namespace {ns}

{HB}
lrat_reflect_cnf leaf{j}_unsat
  (LRATCatcher.Cube.leafCNF {ns}.cube{j} {ns}.F{j}) "data/{a.key}/leaf{j}.lrat"

/-- No lex-minimal biplanar partition of `G` agrees with cube {j}. -/
theorem leaf{j} (planar : List Biplanar.Edge → Prop)
    (H2 : ∀ (S : List Biplanar.Edge) (c : Biplanar.KurCert), c.valid S = true → ¬ planar S) :
    ¬ ∃ σ : Nat → Bool, σ 0 = false ∧ Biplanar.lexOK G gens σ = true ∧
        cube{j}.sat (Biplanar.valSym G gens G.edges.length σ) = true ∧
        planar (Biplanar.part G σ false) ∧ planar (Biplanar.part G σ true) :=
  Biplanar.not_biplanar_on_cube_of_unsat_sym₀ G ws{j} gens cube{j} (by native_decide)
    (by native_decide) (by native_decide) leaf{j}_unsat planar H2

end {ns}
''')
        if not a.no_registry:
            registry_add(f"{a.key}_{j}", f"{mod}.W{j}", f"{ns}.F{j}")
    open(os.path.join(mdir, "Cover.lean"), "w").write(f'''import {mod}.Cubes

/-! Cover completeness for `{a.key}`: the negated-cubes formula is UNSAT
    (`data/{a.key}/cover.lrat`), so every assignment satisfies some cube. -/

namespace {ns}

lrat_reflect_cnf cover_unsat (LRATCatcher.negCubesCNF {ns}.cubes) "data/{a.key}/cover.lrat"

end {ns}
''')
    imports = "\n".join(f"import {mod}.Leaf{j}" for j in range(1, L + 1))
    pattern = " | ".join(["rfl"] * L)
    cases = "\n".join(f"      · exact leaf{j} planar H2" for j in range(1, L + 1))
    open(os.path.join(LEAN, "Biplanar", "Instances", f"{a.name}.lean"), "w").write(f'''{imports}
import {mod}.Cover
import Biplanar.Sym

/-! Certified non-biplanarity of `{a.key}` ({a.doc}) by the split route:
    {L} cubes, each refuted from its own witness set and certificate (one
    `native_decide` per LRAT, in its own module), composed over the per-cube
    statements by `Biplanar.not_biplanar_of_cover` together with the cover
    certificate (generated by verifier/lean_split_modules.py). -/

namespace {ns}

{HB}
/-- **Conditional non-biplanarity theorem (Stage 2, counter-free, split route).**
    For every predicate `planar` on edge lists satisfying the elementary
    direction of Kuratowski's theorem (H2) and isomorphism invariance (H3),
    the graph `G` admits no partition of its edges into two `planar` parts. -/
theorem not_biplanar (planar : List Biplanar.Edge → Prop)
    (H2 : ∀ (S : List Biplanar.Edge) (c : Biplanar.KurCert), c.valid S = true → ¬ planar S)
    (H3 : Biplanar.IsoInvariant G planar) :
    ¬ Biplanar.Biplanar planar G :=
  Biplanar.not_biplanar_of_cover G gens cubes (by native_decide) (by native_decide)
    planar H3 cover_unsat (by
      intro c hc
      simp only [cubes, List.mem_cons, List.not_mem_nil, or_false] at hc
      rcases hc with {pattern}
{cases})

#print axioms not_biplanar

end {ns}
''')
    print(f"wrote {mdir}/{{Base,Cubes,Cover,W1..{L},Leaf1..{L}}}.lean and {a.name}.lean"
          + ("" if a.no_registry else f"; registered {a.key}_1..{a.key}_{L}"))


if __name__ == "__main__":
    main()
