import Biplanar.Instances.A4M13S.Leaf1
import Biplanar.Instances.A4M13S.Leaf2
import Biplanar.Instances.A4M13S.Leaf3
import Biplanar.Instances.A4M13S.Leaf4
import Biplanar.Instances.A4M13S.Leaf5
import Biplanar.Instances.A4M13S.Leaf6
import Biplanar.Instances.A4M13S.Leaf7
import Biplanar.Instances.A4M13S.Leaf8
import Biplanar.Instances.A4M13S.Leaf9
import Biplanar.Instances.A4M13S.Leaf10
import Biplanar.Instances.A4M13S.Leaf11
import Biplanar.Instances.A4M13S.Leaf12
import Biplanar.Instances.A4M13S.Leaf13
import Biplanar.Instances.A4M13S.Leaf14
import Biplanar.Instances.A4M13S.Leaf15
import Biplanar.Instances.A4M13S.Leaf16
import Biplanar.Instances.A4M13S.Cover
import Biplanar.Sym

/-! Certified non-biplanarity of `a4_m13s` (A4 member 13 of F-034: the line graph L(M) of the 7-vertex multigraph M with multiplicities [05:3 06:5 14:4 15:4 23:6 24:1 26:1 34:1 35:1 46:2] (n = 28); P-008 A(ii) rests on its non-biplanarity) by the split route:
    16 cubes, each refuted from its own witness set and certificate (one
    `native_decide` per LRAT, in its own module), composed over the per-cube
    statements by `Biplanar.not_biplanar_of_cover` together with the cover
    certificate (generated by verifier/lean_split_modules.py). -/

namespace Biplanar.A4M13S

-- `native_decide` reflection is cheap at run time, but a declaration's
-- checks share one elaboration budget and the default trips on large
-- witness lists. Raising it changes no axiom.
set_option maxHeartbeats 2000000

/-- **Conditional non-biplanarity theorem (Stage 2, counter-free, split route).**
    For every predicate `planar` on edge lists satisfying the elementary
    direction of Kuratowski's theorem (H2) and isomorphism invariance (H3),
    the graph `G` admits no partition of its edges into two `planar` parts. -/
theorem not_biplanar (planar : List Biplanar.Edge → Prop)
    (H2 : ∀ (S : List Biplanar.Edge) (c : Biplanar.KurCert), c.valid S = true → ¬ planar S)
    (H3 : Biplanar.IsoInvariant G planar) :
    ¬ Biplanar.Biplanar planar G :=
  Biplanar.not_biplanar_of_cover G gens cubes (by native_decide) (by native_decide)
    planar H3 cover_unsat (by
      intro c hc
      simp only [cubes, List.mem_cons, List.not_mem_nil, or_false] at hc
      rcases hc with rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl
      · exact leaf1 planar H2
      · exact leaf2 planar H2
      · exact leaf3 planar H2
      · exact leaf4 planar H2
      · exact leaf5 planar H2
      · exact leaf6 planar H2
      · exact leaf7 planar H2
      · exact leaf8 planar H2
      · exact leaf9 planar H2
      · exact leaf10 planar H2
      · exact leaf11 planar H2
      · exact leaf12 planar H2
      · exact leaf13 planar H2
      · exact leaf14 planar H2
      · exact leaf15 planar H2
      · exact leaf16 planar H2)

#print axioms not_biplanar

end Biplanar.A4M13S
